greeting-service:
  ribbon:
    ReadTimeout: 5000
    ConnectTimeout: 5000
    eureka:
      enabled: false
    listOfServers: localhost:10001,localhost:10002
    ServerListRefreshInterval:  15000

feign:
  hystrix:
    enabled: true

bubu:
  x-auth: foo